name: Deploy UiPath Project

on:
  push:
    branches:
      - main

env:
  ORCH_URL: "https://orchestrator.oz.com/"
  ORCH_TENANT: uipatht
  ORCH_CLIENT_ID: 8DEv1AMNXczW3y4U15LL3jYf62jK93n5
  ORCH_USER_KEY: ovb5Ud4iZJYGhHMNT0Z7NcT7Hx4bDib32ujFCuZsw2mOq
  ORCH_USER_NAME: admin
  ORCH_USER_PWD: Asif@1234
  CLI_URL: "https://uipath.pkgs.visualstudio.com/Public.Feeds/_packaging/UiPath-Official/nuget/v3/flat2/UiPath.CLI.Windows/23.10.9076.19285/UiPath.CLI.Windows.23.10.9076.19285.nupkg"

jobs:
  print-details:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"

  cleaner:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          # Note: For Windows, use Remove-Item instead of rm -rf
          Remove-Item -Path "${{ github.workspace }}" -Recurse -Force -ErrorAction SilentlyContinue

  build-uipath-nuget-package:
    needs: cleaner
    runs-on: [self-hosted, windows, x64]
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Nuget Package
        shell: powershell
        run: ${{ github.workspace }}\scripts\UiPathPack.ps1 ${{ github.workspace }}\project.json -destination_folder ${{ github.workspace }}\package -autoVersion -cli_url ${{ env.CLI_URL }}
      - name: Upload UiPath Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            package/*.*
            scripts/*.ps1

  publish-uipath-nuget-package-Dev:
    needs: build-uipath-nuget-package
    runs-on: [self-hosted, windows, x64]
    steps: 
      - name: Download UiPath Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: ${{ github.workspace }}
      - name: Publish Nuget Package to DEV
        shell: powershell
        run: |
          ${{ github.workspace }}\scripts\UiPathDeploy.ps1 -packages_path ${{ github.workspace }}\package -orchestrator_url ${{ env.ORCH_URL }} -orchestrator_tenant ${{ env.ORCH_TENANT }} -orchestrator_user ${{ env.ORCH_USER_NAME }} -orchestrator_pass ${{ env.ORCH_USER_PWD }} -cli_url ${{ env.CLI_URL }}
